In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [4]:
y.grad_fn

In [5]:
x.grad_fn

Each tensor has a `.grad_fn` attribute that references a Function that has created the `Tensor` (except for Tensors created by the user - their `grad_fn` is `None`).

In [7]:
z = y*y*3
out = z.mean()

In [8]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [9]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [11]:
a = torch.randn(2, 2)
z = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [12]:
out.backward()

In [14]:
x.grad  #Print gradients d(out)/dx

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

`torch.autograd` is an engine for computing vector-Jacobian product.

In [17]:
x = torch.randn(3, requires_grad=True)

y = x*2
while y.data.norm() < 1000:
    y = y*2

y

tensor([ -204.0584, -1435.1555,   914.1040], grad_fn=<MulBackward0>)

In [18]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

x.grad

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])

In [19]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


Or by using `.detach()` to get a new Tensor with the same content but that does not require gradients:

In [22]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)


In [23]:
x.eq(y)

tensor([True, True, True])