In [1]:
import torch 

从接口的角度来讲，对tensor的操作可分为两类：
+ torch.function，如torch.save等。
+ 另一类是tensor.function，如tensor.view等。

而从存储的角度来讲，对tensor的操作又可分为两类：

+ 不会修改自身的数据，如 a.add(b)， 加法的结果会返回一个新的tensor。
+ 会修改自身的数据，如 a.add_(b)， 加法的结果仍存储在a中，a被修改了。

In [2]:
a = torch.Tensor(2, 3)

In [3]:
a

tensor([[7.5558e+23, 1.8106e+22, 1.6020e-19],
        [4.4721e+21, 5.8788e+22, 2.7946e+20]])

In [4]:
b = torch.Tensor([[1,2,3],[4,5,6]])

In [5]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
b.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [7]:
b.size()

torch.Size([2, 3])

In [8]:
b.numel()

6

In [9]:
c = torch.Tensor(b.size())

In [10]:
c

tensor([[6.8243e-07, 1.0130e-11, 3.3243e+21],
        [5.2006e+22, 1.0384e+21, 1.6148e-07]])

In [12]:
c.shape, c.size()

(torch.Size([2, 3]), torch.Size([2, 3]))

t.Tensor(*sizes)创建tensor时，系统不会马上分配空间，只是会计算剩余的内存是否足够使用，使用到tensor时才会分配

In [13]:
torch.linspace(1, 10, 3)

tensor([ 1.0000,  5.5000, 10.0000])

In [14]:
scalar = torch.tensor(3.1)
scalar

tensor(3.1000)

In [18]:
a = torch.arange(0,6)
a.view(2, 3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [19]:
b = a.view(-1, 3)
b.shape

torch.Size([2, 3])

In [20]:
b.unsqueeze(1)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [22]:
b[:,None].shape

torch.Size([2, 1, 3])

In [23]:
b.unsqueeze(-2)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [24]:
c = b.view(1, 1, 1, 2, 3)
c.squeeze(0)

tensor([[[[0, 1, 2],
          [3, 4, 5]]]])

In [25]:
c.shape

torch.Size([1, 1, 1, 2, 3])

In [26]:
c.squeeze()

tensor([[0, 1, 2],
        [3, 4, 5]])

In [27]:
a[1] = 100

In [28]:
b

tensor([[  0, 100,   2],
        [  3,   4,   5]])

In [29]:
a

tensor([  0, 100,   2,   3,   4,   5])

In [30]:
a = torch.randn(3, 4)

In [31]:
a[:,0]

tensor([-1.5660, -0.5812,  0.5412])

In [32]:
a

tensor([[-1.5660, -0.0669,  0.3313, -2.1694],
        [-0.5812,  0.5999, -0.7570, -0.4177],
        [ 0.5412,  0.0962, -0.8285, -0.0367]])

In [33]:
a[:2, 0:2]

tensor([[-1.5660, -0.0669],
        [-0.5812,  0.5999]])

In [35]:
# None类似于np.newaxis, 为a新增了一个轴
a[None].shape

torch.Size([1, 3, 4])

In [36]:
a[:,None,:].shape

torch.Size([3, 1, 4])

In [37]:
a[:,None,None].shape

torch.Size([3, 1, 1, 4])

In [38]:
a>1

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [39]:
a[a>1]

tensor([])

In [40]:
torch.LongTensor([0,1])

tensor([0, 1])

In [41]:
a[torch.LongTensor([0,1])]

tensor([[-1.5660, -0.0669,  0.3313, -2.1694],
        [-0.5812,  0.5999, -0.7570, -0.4177]])

In [48]:
a = torch.arange(0, 16).view(4,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [47]:
index = torch.LongTensor([[0,1,2,3]])
a.gather(0, index)

tensor([[ 0,  5, 10, 15]])

out[i][j] = input[index[i][j]][j]  # if dim == 0

In [50]:
a.shape

torch.Size([4, 4])

In [51]:
import numpy as np

a = np.ones([2,3], dtype=np.float32)

In [52]:
a

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [53]:
b = torch.from_numpy(a)

In [54]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [56]:
b = torch.Tensor(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [57]:
b.numpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [58]:
a = np.ones([2,3])
a.dtype

dtype('float64')

In [60]:
b = torch.Tensor(a)
b.dtype

torch.float32

In [61]:
c = torch.from_numpy(a)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [62]:
a[0,1] = 100

In [63]:
c

tensor([[  1., 100.,   1.],
        [  1.,   1.,   1.]], dtype=torch.float64)

In [64]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [66]:
a = torch.arange(0,6)

In [67]:
a.storage()

 0
 1
 2
 3
 4
 5
[torch.LongStorage of size 6]

In [69]:
b = a.view(2, 3)
b.storage()

 0
 1
 2
 3
 4
 5
[torch.LongStorage of size 6]

In [70]:
id(b.storage()) == id(a.storage())

True

In [71]:
a[1] = 100

In [72]:
b

tensor([[  0, 100,   2],
        [  3,   4,   5]])

a,b 共享storage

In [73]:
c = a[2:]
c.storage()

 0
 100
 2
 3
 4
 5
[torch.LongStorage of size 6]

In [74]:
c.data_ptr(), a.data_ptr()

(140287317388880, 140287317388864)

In [75]:
c[0] = -100
a

tensor([   0,  100, -100,    3,    4,    5])

In [76]:
a.storage_offset(), b.storage_offset(), c.storage_offset()

(0, 0, 2)

可见绝大多数操作并不修改tensor的数据，而只是修改了tensor的头信息。这种做法更节省内存，同时提升了处理速度。

In [80]:
def for_loop_add(x, y):
    result = []
    for i,j in zip(x, y):
        result.append(i+j)
    return torch.Tensor(result)

In [82]:
x = torch.zeros(100)
y = torch.ones(100)
%timeit -n 10 for_loop_add(x,y)
%timeit -n 10 x+y

1.18 ms ± 167 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
The slowest run took 18.12 times longer than the fastest. This could mean that an intermediate result is being cached.
10 µs ± 17.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [84]:
a = torch.randn(2, 3)
a

tensor([[-0.8317,  0.1141,  1.1257],
        [-0.6266, -1.5279, -0.2555]])

In [85]:
torch.set_printoptions(precision=10)
a

tensor([[-0.8316692710,  0.1141416654,  1.1256858110],
        [-0.6265739202, -1.5279184580, -0.2555387914]])